name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # everyday update
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # --- BASIC ---
          user: masud744
          template: classic
          base: header, activity, community, repositories, metadata

          # --- LANGUAGES GRAPH ---
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_analysis_timeout: 15

          # --- OPTIONAL CLEANUP ---
          plugin_languages_ignored: html, css
